export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const RESET_COUNTER = "RESET_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const CHANGE_MULTIPLIER = "CHANGE_MULTIPLIER";
